// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ii9NJpq0-r6KxzshwmzZBCq3J6nONwM',
    appId: '1:715942611896:web:7111fc4dde06c0cb4b5d4d',
    messagingSenderId: '715942611896',
    projectId: 'pry-chat-app',
    authDomain: 'pry-chat-app.firebaseapp.com',
    storageBucket: 'pry-chat-app.firebasestorage.app',
    measurementId: 'G-D4LYQ692LD',
    databaseURL: 'https://pry-chat-app-default-rtdb.firebaseio.com',
  );


  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QjOjMiN00B5Rgdqot15GBPvIHhCwwE0',
    appId: '1:715942611896:android:f96ca8495af811eb4b5d4d',
    messagingSenderId: '715942611896',
    projectId: 'pry-chat-app',
    storageBucket: 'pry-chat-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlQhngE9PFWfR2kB09RPkMO0Z8HT3SihE',
    appId: '1:715942611896:ios:c7773bbdf29e2d6a4b5d4d',
    messagingSenderId: '715942611896',
    projectId: 'pry-chat-app',
    storageBucket: 'pry-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.pryChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlQhngE9PFWfR2kB09RPkMO0Z8HT3SihE',
    appId: '1:715942611896:ios:c7773bbdf29e2d6a4b5d4d',
    messagingSenderId: '715942611896',
    projectId: 'pry-chat-app',
    storageBucket: 'pry-chat-app.firebasestorage.app',
    iosBundleId: 'com.example.pryChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ii9NJpq0-r6KxzshwmzZBCq3J6nONwM',
    appId: '1:715942611896:web:174d105ebb542c124b5d4d',
    messagingSenderId: '715942611896',
    projectId: 'pry-chat-app',
    authDomain: 'pry-chat-app.firebaseapp.com',
    storageBucket: 'pry-chat-app.firebasestorage.app',
    measurementId: 'G-CB1SBWDLNS',
  );
}
